### ISSUE TITLE
marginX in newText creating a new line on the text

### ISSUE THREAD

**Issue by renatosc** [dmccuskey/DMC-Corona-UI#4]
Hi there.

Just download your dmc_ui to take advantage of the auto ellipses.  So, I created a new text using and it works fine (the truncation). But I noticed that if I added a marginX, all the text is moved to the right and instead of creating a new truncations, it keeps the former one and the text now takes 2 lines.

Example:

local txt1 = dUI.newText{
        text = "hello there",
        style={
            width=65,
            height=25,
            align='left',
            fontSize=16,
            fillColor={0.5,0,0.25},
            textColor={1,0,0},
        }
    }

truncates OK and I see on the simulator:  "hello t...".

now, using it with a marginX:

local txt1 = dUI.newText{
        text = "hello there",
        style={
            width=65,
            height=25,
            align='left',
            fontSize=16,
            marginX=10,
            fillColor={0.5,0,0.25},
            textColor={1,0,0},
        }
    }
the text appears taking 2 lines:  "hello [\n]t..."  where I am using [\n] denote the new line.

**Comment by dmccuskey** [comment]
thanks for bringing that to my attention – i pushed a fix to Master.
let me know if you have any other issues.
