### ISSUE TITLE
module 'dmc_events_mix' not found

### ISSUE THREAD

**Issue by yourichng** [dmccuskey/DMC-Corona-UI#5]
Module 'dmc_events_mix' not found:resource (dmc_events_mix.lu) does not exist in archive
    no field package.preload['dmc_events_mix']
    no file '/Users/E/Library/Application Support/Corona/Simulator/Plugins/dmc_events_mix.lua'
    no file '/Users/E/Documents/freisagen/dmc_events_mix.lua'
    no file '/Applications/CoronaSDK/Corona Simulator.app/Contents/Resources/dmc_events_mix.lua'
    no file '/Users/E/Library/Application Support/Corona/Simulator/Plugins/dmc_events_mix.dylib'
    no file './dmc_events_mix.dylib'
    no file '/Applications/CoronaSDK/Corona Simulator.app/Contents/Resources/dmc_events_mix.dylib'

stack traceback:
    [C]: in function 'require'
    ?: in function 'require'
    lib/dmc_ui.lua:121: in main chunk
    [C]: in function 'require'
    ?: in function 'require'
    main.lua:9: in main chunk

After loading the lib folder in your project folder Corona whole When I use require the above error occurs.

Create a blank project, and then insert only one line is local dUI = require 'lib.dmc_ui'.

dmc_corona folder, and there is a file called dmc_events_mix.

**Comment by dmccuskey** [comment]
sounds like you're missing some config files for dmc-corona – i was just looking over the install instructions for dmc-ui and realized that they are incomplete. :( i'll get them updated today, but until then, just make sure you have both: dmc_corona_boot.lua and dmc_corona.cfg at the root-level of your project. then check LUA_PATH in dmc_corona.cfg to ensure it matches your layout (eg, lib/dmc_corona).

for more info the installation instructions for dmc-corona can be found here: http://docs.davidmccuskey.com/setup+and+installation
